name: "Check for TODOs and create or update issues"

on: ["push"]

permissions:
  issues: write
  contents: read

jobs:
  todo-issues:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Check for TODOs and create or update issues"
        uses: "alstr/todo-to-issue-action@v4"
        id: "todo"
